baseURL: https://lyli.website/
languageCode: en-us
title: Lyli
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  homeInfoParams:
      Title: "Welcome to Lyli home page \U0001F44B"
      Content:  Click to [Download](https://drive.google.com/file/d/1O_OPeZcQjJI6gxcqdrfnZBLZzzloZCKV/view?usp=sharing)  the latest release.  The app finds and correct files corrupted by the **.lyli** virus.  Check the **About** page gives more information about the app and the virus. ![screenshot](/images/app-on-laptop.png)
                
menu:
    main:
        - identifier: About
          name: About
          url: /about/
          weight: 40
        - identifier: Story
          name: Story
          url: /story/
          weight: 30
