baseURL: https://lyli-website.onrender.com/
languageCode: en-us
title: Lyli
theme: PaperMod

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

params:
  homeInfoParams:
      Title: ".Lyli \U0001F44B"
      Content: Download the latest release.
               ![ a signals and slots image ](/images/Lyli/Slide1.JPG) 

                
  
